version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=123456789
      - ES_JAVA_HOME=/usr/share/elasticsearch/jdk
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD="123456789"
    ports:
      - '5601:5601'
volumes:
  esdata1:
    driver: local
